### ISSUE TITLE
Docker image (latest) throws Unhandled exception for null parameter

### ISSUE THREAD

**Issue by thehaven** [taylorbobaylor/TrailerDownloader#18]
Just gave the docker image a quick go and unfortunately its throwing Unhandled exceptions as shown below, let me know if you need any more information.

```bash
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET https://api.themoviedb.org/3/search/movie?language=en-US&query=T2.Trainspotting.2017&year=&api_key=e438e2812f17faa299396505f2b375bb
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 134
   at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by taylorbobaylor** [comment]
It looks like you movie title has periods in it and is causing the issue:
https://api.themoviedb.org/3/search/movie?language=en-US&query=T2.Trainspotting.2017&year=&api_key=e438e2812f17faa299396505f2b375bb

If it didn't you can see my API call would have results:
https://api.themoviedb.org/3/search/movie?language=en-US&query=Trainspotting&year=2017&api_key=e438e2812f17faa299396505f2b375bb

This app requires a very specific folder structure layout.

**Comment by thehaven** [comment]
Thanks for looking, I think a lot of folks (myself included) replace white space with periods in our folder structures. Would it be a lot of work to add a feature to normalise against the use of underscores and periods, as sepertor characters, instead of whitespace?

My current layout follows this structure - including for clarity:
```
{Movie.Title}.{Release.Year}.
```
