### ISSUE TITLE
Set a Schedule for downloading

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [taylorbobaylor/TrailerDownloader#23]
I'k using this in conjuntion with radarr which downloads  new movies every day, is there a way to automatically download new trailers?

**Comment by taylorbobaylor** [comment]
No, not right now. I was looking into that a while ago but then got busy. When I find some time I'll try to implement this.

**Comment by YOZZOPANOZZO** [comment]
Thanks, the tool is already working flawlessly as it is but an auto download feature along  with the option to download higher resolution trailers would really be awesome

**Comment by taylorbobaylor** [comment]
Hey @YOZZOPANOZZO 

Had some free time this weekend and made a beta auto download feature.
Could you try using this [docker image](https://hub.docker.com/layers/264022125/taylorbobaylor/movie-trailer-downloader/autodownloads/images/sha256-fba28e74a4773a4c313c9a131acec78683cc9790d72067d346a9b3a23837fd30?context=repo) and let me know how it works for you?

**Comment by dmike3** [comment]
Thanks, just installed the docker beta auto download feature.

**Comment by dmike3** [comment]
> Hey @YOZZOPANOZZO
> 
> Had some free time this weekend and made a beta auto download feature. Could you try using this [docker image](https://hub.docker.com/layers/264022125/taylorbobaylor/movie-trailer-downloader/autodownloads/images/sha256-fba28e74a4773a4c313c9a131acec78683cc9790d72067d346a9b3a23837fd30?context=repo) and let me know how it works for you?

Does this constantly keep trying to download trailers forever? Does it re-download over existing ones, or is it just trying to download the missing ones it can't find?

**Comment by taylorbobaylor** [comment]
Yeah it will keep trying to download any missing trailers.

**Comment by saschabrockel** [comment]
@taylorbobaylor create it for arm64 too and I'll test it for you :)

**Comment by taylorbobaylor** [comment]
@saschabrockel Awesome, I just updated the [docker image](https://hub.docker.com/layers/264022125/taylorbobaylor/movie-trailer-downloader/autodownloads/images/sha256-7f4e3579592e2a78c9e116454d35138e91eb37bf667fd023e086df1d46065cfe?context=repo) for arm64 as well 😄 
Let me know if you run into any issues

**Comment by saschabrockel** [comment]
@taylorbobaylor okay I got it running. So one question, what is the schedule or how to set my own schedule like every 6 hours or something similar? Is there already an option? If the automatic download will work it is the best app on the market/internet in conjunction with Radarr to download trailers.

**Comment by taylorbobaylor** [comment]
@saschabrockel hahahaahah, thanks. Really should have named it Trailarr or something. 😛 
Right now there's no way to set it. It's every 15 seconds as you can see here.
https://github.com/taylorbobaylor/TrailerDownloader/blob/906590832ac6ad41f4f57c9ec3286b37cf57c0d6/TrailerDownloader/Helpers/AutoDownloadHelper.cs#L36

Let me know how it works! I haven't had any problems.

**Comment by saschabrockel** [comment]
Can I see it running in the logs of the container or somewhere? Because I got a missing trailer for a movie now and nothing is happening. The container is running.

**Comment by taylorbobaylor** [comment]
@saschabrockel Yeah you should see something like this in logs of container. These are from mine just now.
```log
[23:06:49 INF] Auto download started
[23:07:04 INF] Auto download started
[23:07:19 INF] Auto download started
[23:07:27 INF] Successfully downloaded trailer for 1917
[23:07:30 INF] Successfully downloaded trailer for 21
[23:07:32 INF] Successfully downloaded trailer for 21 Jump Street
[23:07:47 INF] Auto download started

**Comment by saschabrockel** [comment]
Hmm does not look good then:
`[22:05:34 INF] Starting application...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {72e87da2-0c1b-4f94-9166-f98ba24f37ca} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
[22:07:47 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[22:12:38 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[22:13:11 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[22:54:34 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254`

Don't worry about the errors. I got them also before but I don't recognize that anything is not working.

**Comment by taylorbobaylor** [comment]
Oh wow.... That's odd... That a 401 unauthorized trying to get the movie info using the API key. I'm not seeing this error for some reason.

**Comment by saschabrockel** [comment]
@taylorbobaylor I have seen this quite often in my container but when I reloaded the website and clicked the button to download all missing trailers again it worked. So I don't really care. But I can't see what you expected. There is not even a single "Auto download started" log message.

**Comment by taylorbobaylor** [comment]
@saschabrockel Very strange... If you're on the new image you shouldn't even have an option to Download all missing trailers.... You should have to redo the setup and you'll see an option to enable auto downloads.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/25238885/186285972-1c540e00-c0ca-4811-8dc3-6ffeec4750bb.png">

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/25238885/186286006-c77ccda7-a858-484a-9d4a-5dd740b76ee8.png">

**Comment by saschabrockel** [comment]
For me it looks like this: 
![image](https://user-images.githubusercontent.com/33376463/186286288-b43db7d8-b9a1-4df9-86dc-e46abc127e39.png)

Something is very strange. You have to know before I mounted the config.json on my hard drive:

```
  trailer-downloader:
    image: taylorbobaylor/movie-trailer-downloader:autodownloads
    container_name: trailer-downloader
    ports:
      - 6868:80
    volumes:
      - ${SYNOLOGY}/multimedia/movies:/movies
      - ${APPDATA}/mediaserver/trailer-downloader/config.json:/app/config.json
```

I deleted the folder and removed the volume for config.json because otherwise, I had some internal permission problems anyway. In the meantime when I had these permission problems I could see that there were the two input fields and the slider. But somehow the slider now disappeared as I removed the config.json volume. I really have no idea why. But I can see the flag is not set: `{"MediaDirectory":"/movies","TrailerLanguage":"de-DE","AutoDownload":false}`

I guess I can also use my old instance and just have to manually add the AutoDownload flag.

**Comment by taylorbobaylor** [comment]
Yeah I'd try removing all versions of the image and remove `${APPDATA}/mediaserver/trailer-downloader/config.json` and spin it up again. It seems to be fine on my end....

**Comment by saschabrockel** [comment]
Btw if I start up the container and then go to the frontend I always get an error:
![image](https://user-images.githubusercontent.com/33376463/186287926-d33ee384-7155-47dc-957e-cc4c61463602.png)

```
Error: Failed to invoke 'getAllMoviesInfo' due to an error on the server.
    at _callbacks.<computed> (main-es2015.a2ddde416280c70e3183.js:1:195491)
    at Dh._processIncomingData (main-es2015.a2ddde416280c70e3183.js:1:196617)
    at Dh.connection.onreceive (main-es2015.a2ddde416280c70e3183.js:1:190851)
    at s.onmessage [as __zone_symbol__ON_PROPERTYmessage] (main-es2015.a2ddde416280c70e3183.js:1:174998)
    at WebSocket.T (polyfills-es2015.95bb65e853d2781ac3bd.js:1:16700)
    at l.invokeTask (polyfills-es2015.95bb65e853d2781ac3bd.js:1:7242)
    at i.runTask (polyfills-es2015.95bb65e853d2781ac3bd.js:1:2651)
    at u.invokeTask [as invoke] (polyfills-es2015.95bb65e853d2781ac3bd.js:1:8292)
    at p (polyfills-es2015.95bb65e853d2781ac3bd.js:1:20575)
    at WebSocket.f (polyfills-es2015.95bb65e853d2781ac3bd.js:1:20820)
```

But the auto download seems to work:

```
[00:15:26 INF] Starting application...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {1054da97-b460-4b20-8f4e-8eab044757f2} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
[00:18:11 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 222
[00:18:12 INF] Auto download started
[00:18:15 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[00:18:19 INF] Successfully downloaded trailer for Extraction
[00:18:20 INF] Successfully downloaded trailer for Straight Shooter
[00:18:21 INF] Successfully downloaded trailer for Top Gun Maverick
[00:18:36 INF] Auto download started
[00:18:39 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[00:18:41 INF] Successfully downloaded trailer for Extraction
[00:18:56 INF] Auto download started
[00:18:58 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[00:18:59 INF] Successfully downloaded trailer for Extraction
```

**Comment by taylorbobaylor** [comment]
Hmmmm interesting. Let me know if it continues to work for ya! Hope it helps.

**Comment by saschabrockel** [comment]
@taylorbobaylor I'm pretty sure it will continue to work.

But we really should have an option to set the schedule. Every 15 seconds the container is using up to 80% of my little CPU which is not so nice :) and C# seems to love eating RAM with reserving 330MiB.

**Comment by taylorbobaylor** [comment]
@saschabrockel I'll take a look at adding that when I get some time. I'm focused on testing if auto download works in general.

**Comment by YOZZOPANOZZO** [comment]
> @taylorbobaylor I'm pretty sure it will continue to work.
> 
> But we really should have an option to set the schedule. Every 15 seconds the container is using up to 80% of my little CPU which is not so nice :) and C# seems to love eating RAM with reserving 330MiB.

Thanks for working on this. 
I agree a way to set a schedule at a specific time would be great. I also noticied that the trailers are downloaded in 720p so a way to select a better quality would be awesome
I had some free time and I tried changing the code so it would always download the trailer in the highest quality. It seems to be working but It's not a clean solution by any means since it has to download video and audio separately then mux them together. Also C# is not really my jam😛.

```
try
            {
                YoutubeClient youtube = new YoutubeClient();
                StreamManifest streamManifest = await youtube.Videos.Streams.GetManifestAsync(movie.TrailerURL);

                // Get highest bit rate audio stream

                IAudioStreamInfo audioStreamInfo = (IAudioStreamInfo)streamManifest.GetAudioStreams().GetWithHighestBitrate();

                // try to get 1080p stream otherwise settle for 720p

                IVideoStreamInfo videoStreamInfo;
                try
                {
                    videoStreamInfo = streamManifest.GetVideoStreams().First(s => s.VideoQuality.Label == "1080p");

                }
                catch (Exception ex){
                    try
                    {
                        videoStreamInfo = streamManifest.GetVideoStreams().First(s => s.VideoQuality.Label == "720p");
                    }
                    catch (Exception ex2) { videoStreamInfo = streamManifest.GetVideoStreams().First(s => s.VideoQuality.Label == "480p"); }
                }
            

                // mux the two streams together into one file

                var streamInfos = new IStreamInfo[] { audioStreamInfo, videoStreamInfo };
 
                //  IVideoStreamInfo streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();


                if (audioStreamInfo != null && videoStreamInfo != null)
                {


                    // Download the stream to file

                    await youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder(Path.Combine(movie.FilePath, $"{movie.Title} ({movie.Year})-trailer.{videoStreamInfo.Container}")).Build());


                    _logger.LogInformation($"Successfully downloaded trailer for {movie.Title}");
                    return true;
                }


                return false;
            }
```

**Comment by taylorbobaylor** [comment]
@YOZZOPANOZZO Okay, I'll look into that when I get some time. Good suggestions. Feel free to make a pull request if you wanna take a stab at it 😄

**Comment by saschabrockel** [comment]
Is it possible to set a fallback language if there is no trailer for my language? I've seen to have some bugs but not with the auto-download feature. If I call the webpage I have to reload 3-4 times because I get so many errors 429 and the images of many movies won't load but then it works. And I have no goddamn idea why it shows me the same success message for a movie I have got the trailer since forever every 15 seconds:

Success!
Done downloading trailer for Extraction

I mean I also see this message in the container logs. 24/7
I guess it has something to do with the auto-download feature huh?

```
[00:23:15 INF] Auto download started
[00:23:17 ERR] Error getting movie info for Mesrine Public Enemy #1
Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api.themoviedb.org/3/search/movie?language=en-US&query=Mesrine%20Public%20Enemy%20#1&year=2008&api_key=e438e2812f17faa299396505f2b375bb
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieInfoAsync(Movie movie) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 254
[00:23:18 INF] Successfully downloaded trailer for Extraction
```

Only this one goddamn movie always crashes and I also already have the trailer for it. But that's what it looks like for me permanently.

**Comment by saschabrockel** [comment]
Since I have this one movie failing all the time no trailers are downloaded anymore sadly. The URL call returns:
`{"status_code":7,"status_message":"Invalid API key: You must be granted a valid key.","success":false}`

**Comment by taylorbobaylor** [comment]
@saschabrockel Those are 401 unauthorized errors. I've never seen that personally. Are you still getting that error?

**Comment by saschabrockel** [comment]
Yep still getting the exact same error just for this movie. @taylorbobaylor
