### ISSUE TITLE
Unhandled exception when loading movies

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [taylorbobaylor/TrailerDownloader#24]
I have been using this for a few days and it working just fine until now. I'm getting this Unhandled exception that causes the program to crash while importing movies, what could be causing this? 

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 134
   at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

**Comment by YOZZOPANOZZO** [comment]
That link does not work for me unfortunately...  I'm getting 404 not found

**Comment by taylorbobaylor** [comment]
What about this?

https://github.com/taylorbobaylor/TrailerDownloader/releases/tag/v1.1.3

**Comment by YOZZOPANOZZO** [comment]
Yes that seems to have fixed it, Thanks!
