### ISSUE TITLE
Value cannot be null (docker)

### ISSUE THREAD

**Issue by VampiricAlien** [taylorbobaylor/TrailerDownloader#35]
One day it was working and the next it wasn't. Only shows 3 menu options. I've checked and checked movie directory, that's the right location and docker is set to access the host path and /movies.

`warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]

      Failed to determine the https port for redirect.

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]

      Failed to invoke hub method 'GetAllMoviesInfo'.

      System.ArgumentNullException: Value cannot be null. (Parameter 'input')

         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)

         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)

         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 136

         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 59

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]

      Failed to invoke hub method 'GetAllMoviesInfo'.

      System.ArgumentNullException: Value cannot be null. (Parameter 'input')

         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)

         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)

         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 136

         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 59

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]

      Failed to invoke hub method 'GetAllMoviesInfo'.

      System.ArgumentNullException: Value cannot be null. (Parameter 'input')

         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)

         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)

         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 136

         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 59

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, 
HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]

      Failed to invoke hub method 'GetAllMoviesInfo'.

      System.ArgumentNullException: Value cannot be null. (Parameter 'input')

         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)

         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)

         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 136

         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in /src/TrailerDownloader/SignalRHubs/MovieHub.cs:line 59

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)

         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)`

**Comment by taylorbobaylor** [comment]
Hey @VampiricAlien - Can you try with the latest release and let me know if you're still having issues?

**Comment by taylorbobaylor** [comment]
@VampiricAlien sorry about that..... Try this one [here](https://hub.docker.com/layers/taylorbobaylor/movie-trailer-downloader/latest/images/sha256-6f79aca9e3dcbbd9f432261e3fe2f1edad94aa779e8c0001a412ff72ec3b37f1?context=repo)

**Comment by taylorbobaylor** [comment]
Hey @VampiricAlien can you pull the latest image and let me know if that works for you?

**Comment by taylorbobaylor** [comment]
Hmmmmmm.... I'm running it fine on my Synology setup..... Can you share you `docker-compose` or `docker run` command you're using? Did you clear out your config.json? Can you if you didn't?

**Comment by taylorbobaylor** [comment]
No looks like it started up fine now. Can you share the command you're using to start the container? Or the section in the docker-compose?

**Comment by taylorbobaylor** [comment]
Did you do a `docker pull` of the latest image before?

**Comment by taylorbobaylor** [comment]
Yeah.... I'm not sure... It's like the user you're running the container under doesn't haver permissions to create files or something.... Can you try running as root user or something to see if that does something?

I can't replicate the issue locally it seems.

**Comment by taylorbobaylor** [comment]
Nice, glad you got it working!

It's downloading the highest quality one available on youtube that it's getting from TMDB API.
https://github.com/taylorbobaylor/TrailerDownloader/blob/3b617849bb0a0e7bcbe9d83d2361dbfb0126c233/TrailerDownloader/SignalRHubs/MovieHub.cs#L189

Is it okay to close this issue now?

**Comment by taylorbobaylor** [comment]
Awesome, glad it's working for you!!! Look out for some updates in the future. Going to make a major refactor 😊
