### ISSUE TITLE
Empty movie folder - System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by tripelbit-dev** [taylorbobaylor/TrailerDownloader#4]
Hey, great little app, turns out that when there's an empty movie folder somewhere in the main movie root, the app crashes:

For example if I scan `Y:\` and there is an empty folder like `Y:\Random Empty Movie folder (2020)` it throws the error below

```
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 112
   at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 55
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by taylorbobaylor** [comment]
Sweet, thank you! I'll take a look at this as soon as I can. 😊

**Comment by taylorbobaylor** [comment]
This should be fixed now if you can try the latest release located [here](https://github.com/taylorbobaylor/TrailerDownloader/releases/latest) and let me know if that works for you!

**Comment by tripelbit-dev** [comment]
I can confirm that this now works for the empty folder that was crashing before, thanks!

**Comment by taylorbobaylor** [comment]
Awesome, hope you enjoy it!!! 😊
