### ISSUE TITLE
Failed to invoke hub method 'GetAllMoviesInfo'.

### ISSUE THREAD

**Issue by Classified711** [taylorbobaylor/TrailerDownloader#57]
Getting the following error when running the app:

warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetAllMoviesInfo'.
      System.ArgumentNullException: Value cannot be null. (Parameter 'input')
         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 135
         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 58
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'GetAllMoviesInfo'.
      System.ArgumentNullException: Value cannot be null. (Parameter 'input')
         at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
         at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
         at TrailerDownloader.SignalRHubs.MovieHub.GetMovieFromDirectory(String movieDirectory) in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 135
         at TrailerDownloader.SignalRHubs.MovieHub.GetAllMoviesInfo() in C:\Users\taylo\source\repos\TrailerDownloader\TrailerDownloader\SignalRHubs\MovieHub.cs:line 58
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

**Comment by untotren** [comment]
same
